config-version: 1

root-folder: ./demo/basics

snowflake-user: {{ env_var('SNOWFLAKE_USER')}}
snowflake-account: {{ env_var('SNOWFLAKE_ACCOUNT')}}
snowflake-role: {{ env_var('SNOWFLAKE_ROLE')}}
snowflake-warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE')}}
snowflake-database: {{ env_var('SNOWFLAKE_DATABASE')}}
snowflake-schema: {{ env_var('MY_TARGET_SCHEMA')}}
change-history-table: "{{ env_var('SNOWFLAKE_DATABASE')}}.{{ env_var('MY_TARGET_SCHEMA')}}.CHANGE_HISTORY"
create-change-history-table: true

vars:
  database_name: {{env_var('SNOWFLAKE_DATABASE', 'SCHEMACHANGE_DEMO')}}
  schema_name: {{env_var('SNOWFLAKE_SCHEMA', 'BASICS_DEMO')}}
