config-version: 1

root-folder: ./demo/citibike

snowflake-user: {{ env_var('SNOWFLAKE_USER')}}
snowflake-account: {{ env_var('SNOWFLAKE_ACCOUNT')}}
snowflake-role: SCHEMACHANGE_DEMO_DEPLOY
snowflake-warehouse: SCHEMACHANGE_DEMO_WH
snowflake-database: SCHEMACHANGE_DEMO
snowflake-schema: CITIBIKE_DEMO
change-history-table: "SCHEMACHANGE_DEMO.SCHEMACHANGE.CHANGE_HISTORY"
create-change-history-table: true

