config-version: 1

root-folder: "./demo/{{ env_var('SCENARIO_NAME')}}/2_test"
modules-folder: "./demo/{{ env_var('SCENARIO_NAME')}}/modules"

change-history-table: "{{ env_var('SNOWFLAKE_DATABASE')}}.{{ env_var('MY_TARGET_SCHEMA')}}.CHANGE_HISTORY"
create-change-history-table: true

vars:
  database_name: "{{env_var('SNOWFLAKE_DATABASE')}}"
  schema_name: "{{env_var('MY_TARGET_SCHEMA')}}"
  secrets:
    # not a good example of secrets, just here to demo the secret filtering
    trips_s3_bucket: s3://snowflake-workshop-lab/citibike-trips
    weather_s3_bucket: s3://snowflake-workshop-lab/weather-nyc
